name: Push API
on:
  workflow_run:
    workflows: ["Test Backend"]
    types: [completed]
    branches: [master]

jobs:
  push-backend-api:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    # run only when code is compiling and tests are passing
    runs-on: ubuntu-22.04

    # steps to perform in job
    steps:
      - name: Checkout code
        uses: actions/checkout@v2.5.0

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USR }}
          password: ${{ secrets.DOCKER_PWD }}

      - name: Build image and push backend
        uses: docker/build-push-action@v3
        with:
          context: ./backend/code/simple-api-student/
          tags: ${{secrets.DOCKER_USR}}/simple-api:latest
          push: ${{ github.ref == 'refs/heads/master' }}